// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kuzu_database
Rcpp::XPtr<Database> kuzu_database(Rcpp::Nullable<std::string> db_path);
RcppExport SEXP _kuzuR_kuzu_database(SEXP db_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type db_path(db_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(kuzu_database(db_path));
    return rcpp_result_gen;
END_RCPP
}
// kuzu_connection
Rcpp::XPtr<Connection> kuzu_connection(Rcpp::XPtr<Database> database);
RcppExport SEXP _kuzuR_kuzu_connection(SEXP databaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Database> >::type database(databaseSEXP);
    rcpp_result_gen = Rcpp::wrap(kuzu_connection(database));
    return rcpp_result_gen;
END_RCPP
}
// kuzu_query
Rcpp::List kuzu_query(Rcpp::XPtr<Connection> connection, std::string query);
RcppExport SEXP _kuzuR_kuzu_query(SEXP connectionSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Connection> >::type connection(connectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(kuzu_query(connection, query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kuzuR_kuzu_database", (DL_FUNC) &_kuzuR_kuzu_database, 1},
    {"_kuzuR_kuzu_connection", (DL_FUNC) &_kuzuR_kuzu_connection, 1},
    {"_kuzuR_kuzu_query", (DL_FUNC) &_kuzuR_kuzu_query, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_kuzuR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
