# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a Kuzu database
#' @param db_path Path to database file, or ":memory:" for in-memory
#' @return External pointer to the database
#' @export
kuzu_database <- function(db_path = NULL) {
    .Call('_kuzuR_kuzu_database', PACKAGE = 'kuzuR', db_path)
}

#' Create a connection to a Kuzu database
#' @param database Database object
#' @return External pointer to the connection
#' @export
kuzu_connection <- function(database) {
    .Call('_kuzuR_kuzu_connection', PACKAGE = 'kuzuR', database)
}

#' Execute a query on a Kuzu database
#' @param connection Connection object
#' @param query Cypher query string
#' @return List with query results
#' @export
kuzu_query <- function(connection, query) {
    .Call('_kuzuR_kuzu_query', PACKAGE = 'kuzuR', connection, query)
}

